### ISSUE TITLE
Missing APM transactions since upgrading to HotChocolate 12.0.0-rc.3 and latest

### ISSUE THREAD

**Issue by sergiu-enache** [SwissLife-OSS/elastic-apm-extensions#10]
I've noticed that since I've upgraded to latest 12 version of HotChocolate, specifically since RC 3 I get some differences in Elastic APM.

before RC 3:
![image](https://user-images.githubusercontent.com/77912457/132839483-63733d4a-64f3-474b-8269-5cef29c26cdf.png)

![image](https://user-images.githubusercontent.com/77912457/132839951-9ff3ed0d-87df-4daf-907d-ab2edd3717ea.png)

after RC 3:
![image](https://user-images.githubusercontent.com/77912457/132839522-806be955-1328-44e4-baed-d12db1003de5.png)

![image](https://user-images.githubusercontent.com/77912457/132840057-56fd70ba-8068-4bbd-9aa8-51bc02188fa3.png)

The data still seems to be corelated for Gateway and subgraph.

Not sure if this is an issue with ElasticApm.GraphQL.HotChocolate or HotChocolate introduced a breaking change.

**Comment by glucaci** [comment]
Hi and thanks for reporting. Please try with 2.0.0-preview.1.

**Comment by glucaci** [comment]
I think this is fixed, please create a new one if not.
2.0.0-preview.2 has also the 12 stable release from HC

**Comment by vhatsura** [comment]
> 2.0.0-preview.2 has also the 12 stable release from HC

@glucaci, can you check to publish status of the new version as it's still missed at nuget.org.

Thanks in advance

**Comment by glucaci** [comment]
Done
https://www.nuget.org/packages/ElasticApm.GraphQL.HotChocolate/2.0.0-preview.2
