### ISSUE TITLE
Broken instrumentation with 1.12.0 version of Elastic.Apm

### ISSUE THREAD

**Issue by vhatsura** [SwissLife-OSS/elastic-apm-extensions#14]
**Describe the bug**

Binary compatibility is broken with the latest 1.12.0 version of Elastic.Apm. The `StartSpan` method is extended with the new optional parameter `isExitSpan` which saves compatibility on the source code level, but not in binary one.
The main disadvantage is that it also influences the whole query and no resolvers are called. I think this is another issue that should be resolved in the HotChocolate itself.

**To Reproduce**

Use 2.0.0-preview.1 version of the library with 1.12.0 version of Elastic.Apm.

```
System.MissingMethodException: Method not found: 'Elastic.Apm.Api.ISpan Elastic.Apm.Api.IExecutionSegment.StartSpan(System.String, System.String, System.String, System.String)'.
   at Elastic.Apm.GraphQL.HotChocolate.HotChocolateDiagnosticListener.ResolveFieldValue(IMiddlewareContext context)
   at HotChocolate.Execution.Processing.Tasks.ResolverTask.ExecuteAsync(CancellationToken cancellationToken)
```

**Comment by glucaci** [comment]
With #15 is this issue fixed?
