### ISSUE TITLE
HotChocolate: Console logger issue

### ISSUE THREAD

**Issue by sergiu-enache** [SwissLife-OSS/elastic-apm-extensions#8]
First of all thank you for this package.

Reproduced with https://github.com/ChilliCream/graphql-workshop/tree/v2/schema-federation-with-hotchocolate 

While using the asp.net core default console logger, and throwing an exception from a resolver you get this internel error:

```
{
  "errors": [
    {
      "message": "Unexpected Execution Error"
    }
  ]
}
```

Instead of the expected detailed result:

```
{
  "errors": [
    {
      "message": "Unexpected Execution Error",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "reviewsByAuthor"
      ]
    }
  ],
  "data": {
    "reviewsByAuthor": null
  }
}
```

As a workaround either remove the console logger in the host builder:

```
.ConfigureLogging((hostingContext, logging) =>
{
	logging.ClearProviders();
})
```

or add the LogLevel.None to "Elastic.Apm" category in appsettings.json:

```
"Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information",
      "Elastic.Apm": "None"
    }
  }

```

**Comment by glucaci** [comment]
Thanks for reporting it.
1.0.0-preview.7 is building ;)
